version: "3.7"
services:
    # Update this to the name of the service you want to work with in your docker-compose.yml file
    spring-todo:
        container_name: "spring-todo"

        user: vscode

        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args:
                VARIANT: "15"
                INSTALL_MAVEN: "false"
                INSTALL_GRADLE: "true"
                INSTALL_NODE: "false"
                NODE_VERSION: "lts/*"

        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}

        volumes:
            # Update this to wherever you want VS Code to mount the folder of your project
            - ../:/workspace:cached,Z

        network_mode: host

        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"

    spring-todo-postgres:
        container_name: "spring-todo-postgres"
        image: postgres:13.1
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${postgres_user}
            - POSTGRES_PASSWORD=${postgres_password}
            - POSTGRES_DB=${postgres_db}
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ${PWD}/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
            - spring-todo-postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    spring-todo-postgres:
